# Generated by Django 3.2.8 on 2021-10-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hair'),
    ]

    operations = [
        migrations.AddField(
            model_name='hair',
            name='observation',
            field=models.CharField(max_length=400, null='True'),
            preserve_default='True',
        ),
    ]
