# Generated by Django 3.2.8 on 2021-10-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userhost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhost',
            name='host_email',
            field=models.EmailField(max_length=254),
        ),
    ]
