# Generated by Django 3.2.8 on 2021-10-10 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userhost_host_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=254, null=True)),
                ('userhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookcategory', to='api.userhost')),
            ],
            options={
                'db_table': 'Book_Category',
            },
        ),
    ]
