# Generated by Django 3.2.8 on 2021-10-10 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bookcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcategory',
            name='userhost',
        ),
    ]
