# Generated by Django 3.2.8 on 2021-10-10 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_bookcategory_userhost'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcategory',
            name='userhost',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='bookcategory', to='api.userhost'),
            preserve_default='True',
        ),
    ]
