# Generated by Django 3.2.8 on 2021-10-10 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_bookcategory_userhost'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhost',
            name='bookcategory',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='userhost', to='api.bookcategory'),
            preserve_default='True',
        ),
    ]
