# Generated by Django 3.2.8 on 2021-10-10 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'User_Client',
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='userhost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='api.userhost'),
        ),
    ]
